# Generated by Django 5.0.3 on 2024-03-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0008_accesshistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesshistory',
            options={'verbose_name': 'accesshistory', 'verbose_name_plural': 'accesshistories'},
        ),
    ]
