# Generated by Django 5.0.3 on 2024-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0013_subscriber_stripe_id_subscriber_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, help_text='150文字以内で文字や数字を使うことができます（記号は「@/./+/-/_」のみ使用可能）。', max_length=150, null=True, unique=True, verbose_name='nickname'),
        ),
    ]
